### ISSUE TITLE
Add contributors to the readme

### ISSUE THREAD

**Issue by TomasRoj** [TomasRoj/HactoberFest2019#10]
Hello everybody,

it would be nice to have contributors section with user profile pics so other can start follow them. Such a section is is here for example - https://github.com/blackbird71SR/Code-Portfolios#contributors . Dont worry to finish this issue and make pull request!

**Comment by jasonappah** [comment]
#42 I have done this if you'd like to take a look.

**Comment by TomasRoj** [comment]
Fixed by @jasonappah . Thank you very much!
